name: hello-world-spring-boot

on: [push]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
     
      - uses: docker/login-action@v1
        with:
          username: 'taleevaalam'
          password: 'JK@!#docker980'
      - name: Build docker image
        run: docker build -t helloworld:latest .
      - name: Tag docker image
        run: docker tag helloworld:latest taleevaalam/helloworld:latest
      - name: Push docker image
        run: docker push taleevaalam/helloworld:latest
          
